language: ruby
rvm:
- 2.1

before_script:
 - chmod +x ./script/cibuild



script: ./script/cibuild

language: node_js
node_js:
  - "0.12"

after_success:
 - surge --project _site  --domain itu.codingpirates.dk

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false 
