name: Coding Pirates <br/> ITU
description: Ohøj, pirat! Det her er hjemmesiden for Coding
             Pirates-afdelingen på ITU. <br/>
             Her viser vi en masse seje projekter,
              lavet på de forskellige workshops, på ITU.
markdown: redcarpet
highlighter: true
email: per@codingpirates.dk
twitter: twitterusername
github: githubusername
