name: Coding Pirates <br/> DIKU
description: Hej pirat! Her samler vi praktisk info om Coding Pirates-afdelingen på DIKU.
markdown: redcarpet
pygments: true
email: dybber@dybber.dk
twitter: twitterusername
github: gitusername

